"""
funnel_table.py  --  aggregate per-module end-to-end candidate-reduction funnels
================================================================================
Reads the `funnel` block that field_predict.py writes into each
field_modules/<tag>.predictions.json and prints a multi-module table plus a paste-ready
LaTeX table (regions -> standard-length candidates -> pre-filter survivors -> ML-KEY,
with overall reduction %).

USAGE
-----
    python funnel_table.py --indir field_modules --tex funnel_table.tex
"""
import argparse, glob, json, os


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--indir", default="field_modules")
    ap.add_argument("--tex", default="funnel_table.tex")
    args = ap.parse_args()

    rows = []
    timings = []   # per-module wall-clock from field_predict.py
    for f in sorted(glob.glob(os.path.join(args.indir, "*.predictions.json"))):
        d = json.load(open(f, encoding="utf-8"))
        fn = d.get("funnel")
        if not fn:
            print(f"  [skip] {os.path.basename(f)}: no funnel block "
                  f"(re-run field_predict.py, not field_detect.py)")
            continue
        reg = fn.get("regions_scanned", 0)
        cand = fn.get("std_length_candidates", 0)
        pf = fn.get("prefilter_passed", 0)
        key = fn.get("ml_key_predictions", 0)
        red = (1 - key / cand) * 100 if cand else 0.0
        rows.append({"module": d.get("module", "?"), "library": d.get("library", "?"),
                     "regions": reg, "cand": cand, "pf": pf, "key": key, "red": red})
        t = d.get("timing")
        if t and "detect_s" in t:
            timings.append(t)

    if not rows:
        raise SystemExit("No prediction files with a funnel block. Run field_predict.py "
                         "(with --static-scan and a large --cap) first.")

    # console
    print(f"\n{'Module':<28}{'regions':>9}{'candidates':>14}{'pre-filter':>12}{'ML-KEY':>8}{'reduction':>11}")
    for r in rows:
        print(f"{r['module']:<28}{r['regions']:>9}{r['cand']:>14,}{r['pf']:>12,}{r['key']:>8,}{r['red']:>10.2f}%")

    # per-module wall-clock (from field_predict.py timing block)
    if timings:
        import statistics
        det = [t["detect_s"] for t in timings]
        tot = [t["total_s"] for t in timings if t.get("total_s") is not None]
        line = (f"\nper-module wall-clock (s): detect mean {statistics.mean(det):.1f} "
                f"(min {min(det):.1f}, max {max(det):.1f}) over {len(det)} modules")
        if tot:
            line += f"; total mean {statistics.mean(tot):.1f} (incl. one-time model load)"
        print(line)
    else:
        print("\nper-module wall-clock: no timing block found (re-run field_predict.py to record it).")

    # LaTeX
    def fmt(n):
        return f"{n:,}".replace(",", "{,}")
    body = "\n".join(
        f"{r['module']} & {r['regions']} & {fmt(r['cand'])} & {fmt(r['pf'])} & {fmt(r['key'])} & {r['red']:.2f}\\% \\\\"
        for r in rows)
    tex = (
        "% Auto-generated by funnel_table.py from real field runs.\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{End-to-end candidate reduction of the classifier path per live module "
        "(blind, uncapped scan). Reduction = $1-\\text{ML-KEY}/\\text{candidates}$.}\n"
        "\\label{tab:funnel}\n\\scriptsize\n"
        "\\begin{tabular}{@{}lrrrrr@{}}\n\\toprule\n"
        "\\textbf{Module} & \\textbf{Regions} & \\textbf{Candidates} & \\textbf{Pre-filter} & "
        "\\textbf{ML-KEY} & \\textbf{Reduction} \\\\\n\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n\\end{{table}}\n")
    with open(args.tex, "w", encoding="utf-8") as fh:
        fh.write(tex)
    print(f"\nWrote {args.tex}")


if __name__ == "__main__":
    main()
