"""
pr_roc_dump.py -- KEY-class precision-recall and ROC from the corpus CSV.
=========================================================================
Computes out-of-fold (5-fold stratified CV) KEY-vs-rest probabilities for the deployed
CatBoost, then the PR curve (with average precision), the ROC curve (with AUC), and the
deployment-prior PR curve (KEY base rate pi reweighted to a realistic value). Uses ONLY
the released corpus CSV. Emits:
  * pr_roc.tex  -- two pgfplots axes (PR and ROC) with down-sampled coordinates, ready to
                   \input as Fig. tab/fig:prroc;
  * console summary (AP, AUC, deployment-prior PPV at several thresholds).
No number is hard-coded into the manuscript; \input the .tex after running.

USAGE
-----
    python pr_roc_dump.py --csv dataset/real_crypto_features.csv --prior 1e-4
"""
import argparse, os, sys
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "data_collector"))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from feature_extractor import FEATURE_NAMES

CLASSES = ["KEY", "IV", "CIPHERTEXT", "PLAINTEXT", "NON_CRYPTO"]


def load(csv):
    import pandas as pd
    df = pd.read_csv(csv)
    X = df[FEATURE_NAMES].astype(float).values
    y = (df["label"].astype(str).values == "KEY").astype(int)
    return X, y


def oof_key_proba(X, y, seed=42):
    from sklearn.model_selection import StratifiedKFold
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    proba = np.zeros(len(y), dtype=float)
    # Deployed model: XGBoost (matches run_pathB.py --deployed XGBoost and the manuscript).
    import xgboost as xgb
    def mk():
        return xgb.XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.1,
                                 objective="binary:logistic", eval_metric="logloss",
                                 random_state=seed, verbosity=0)
    for tr, te in skf.split(X, y):
        m = mk(); m.fit(X[tr], y[tr])
        proba[te] = np.asarray(m.predict_proba(X[te]))[:, 1]
    return proba


def downsample(xs, ys, n=60):
    if len(xs) <= n:
        return list(zip(xs, ys))
    idx = np.linspace(0, len(xs) - 1, n).astype(int)
    return list(zip(np.asarray(xs)[idx], np.asarray(ys)[idx]))


def coords(pairs):
    return " ".join(f"({x:.4f},{y:.4f})" for x, y in pairs)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default="dataset/real_crypto_features.csv")
    ap.add_argument("--prior", type=float, default=1e-4, help="deployment KEY base rate")
    ap.add_argument("--tex", default="pr_roc.tex")
    a = ap.parse_args()
    from sklearn.metrics import precision_recall_curve, roc_curve, average_precision_score, roc_auc_score

    X, y = load(a.csv)
    print(f"corpus: {len(y)} blocks, {int(y.sum())} KEY ({100*y.mean():.1f}%)")
    p = oof_key_proba(X, y)
    ap_score = average_precision_score(y, p)
    auc = roc_auc_score(y, p)
    print(f"KEY average precision (AP) = {ap_score:.4f}  |  ROC AUC = {auc:.4f}")

    prec, rec, thr = precision_recall_curve(y, p)
    fpr, tpr, _ = roc_curve(y, p)

    # deployment-prior PPV across recall: PPV = rec*pi / (rec*pi + fpr*(1-pi)); map thresholds.
    print("\ndeployment-prior PPV (pi=%.0e):" % a.prior)
    for thr_v in (0.5, 0.8, 0.9, 0.95):
        tp = ((p >= thr_v) & (y == 1)).sum(); fp = ((p >= thr_v) & (y == 0)).sum()
        r = tp / max(1, y.sum()); fr = fp / max(1, (y == 0).sum())
        ppv = r * a.prior / (r * a.prior + fr * (1 - a.prior)) if (r or fr) else 0.0
        print(f"  thr={thr_v:.2f}: recall={r:.3f} FPR={fr:.4f} -> PPV={ppv*100:.3f}%")

    pr_pairs = downsample(rec[::-1], prec[::-1])     # recall ascending
    roc_pairs = downsample(fpr, tpr)
    tex = (
        "% Auto-generated by pr_roc_dump.py -- VERIFY then \\input.\n"
        "\\begin{figure}[t]\\centering\n"
        "\\begin{tikzpicture}\n\\begin{axis}[width=\\columnwidth,height=4.2cm,\n"
        "  xlabel={Recall},ylabel={Precision},xmin=0,xmax=1,ymin=0,ymax=1.02,\n"
        "  grid=both,tick label style={font=\\scriptsize},label style={font=\\scriptsize}]\n"
        f"\\addplot[thick,mark=none] coordinates {{{coords(pr_pairs)}}};\n"
        "\\end{axis}\\end{tikzpicture}\n"
        f"\\caption{{KEY-class precision--recall (5-fold out-of-fold; average precision "
        f"AP$={ap_score:.3f}$, ROC AUC$={auc:.3f}$). At a deployment prior $\\pi=10^{{-4}}$ the "
        f"standalone PPV stays low (see text), confirming the classifier is a triage stage.}}\n"
        "\\label{fig:prroc}\n\\end{figure}\n"
    )
    open(a.tex, "w", encoding="utf-8").write(tex)
    print(f"\nWrote {a.tex} (AP={ap_score:.3f}, AUC={auc:.3f}). ROC coords also available in console.")
    print("ROC coordinates:", coords(roc_pairs))


if __name__ == "__main__":
    main()
